vim.cmd("set showmode")
vim.cmd("set incsearch")
vim.cmd("set hls")
vim.cmd("set clipboard+=unnamedplus")
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number relativenumber")
vim.g.mapleader = " "
vim.cmd("nmap <A-Left> <C-O>")
